// ESLint flat config — TS + React (T-0.1, Phase 0 apply gate).
//
// Two contexts in this repo need different globals:
//   - `src/**`      → runs in the browser (React app)
//   - root configs  → run under Node (vite.config.ts, vitest.config.ts, this file)
//
// `eslintConfigPrettier` MUST be last so it can turn off any ESLint stylistic
// rule that would conflict with Prettier (T-0.2) — Prettier owns formatting,
// ESLint owns correctness.
import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import eslintConfigPrettier from 'eslint-config-prettier'

export default tseslint.config(
  {
    // `database.types.ts` is generated by `supabase gen types` (T-0.5) — not
    // hand-written, not worth linting/formatting like the rest of `src/`.
    ignores: ['dist', 'dev-dist', 'coverage', 'src/lib/database.types.ts'],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      reactHooks.configs.flat['recommended-latest'],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
  },
  {
    files: ['*.config.{js,ts}'],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    // Route config, not a component module: `react-refresh/only-export-components`
    // flags every local `const X = lazy(...)` binding here because the file's
    // only export (`router`) isn't itself a component — a known false positive
    // for lazy-loaded router files (the plugin can't see that HMR boundaries
    // don't matter for this file). Scoped to this one file, not the rule globally.
    files: ['src/lib/router.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  eslintConfigPrettier
)
